App::Assixt:
  only:
    - master
  image: rakudo-star
  before_script:
    - apt update -qq && apt install -yqq build-essential
    - zef install . --deps-only --/test
  script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t
  artifacts:
    name: "perl6-App-Assixt"
    paths:
      - META6.json
      - bin
      - lib
      - resources
      - t

test:
  except:
    - master
  image: rakudo-star
  before_script:
    - apt update -qq && apt install -yqq build-essential
    - zef install . --deps-only --/test
  script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t
